@extends('components.main')
@section('content')

<div class="container py-10 px-6 mx-auto max-w-4xl">
    <h1 class="text-center text-3xl font-bold text-gray-800 mb-4">Terms &amp; Conditions</h1>
    <p class="text-gray-700 leading-relaxed bg-gray-100 p-4 rounded-lg shadow-md">
        <strong>This document is an electronic record</strong> in terms of the Information Technology Act, 2000, and
        rules thereunder,
        as applicable, along with the amended provisions pertaining to electronic records in various statutes as amended
        by the Information Technology Act, 2000.
        This electronic record is generated by a computer system and does not require any physical or digital
        signatures.
    </p>

    <section class="mb-5 p-6 bg-gray-100 rounded-lg shadow-md">
        {{-- <h2 class="text-2xl font-semibold text-gray-800 mb-4">1. Introduction</h2> --}}
        <p class="text-gray-700 leading-relaxed">
            This document is published in accordance with the provisions of
            <span class="font-medium">Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules,
                2011</span>,
            which requires publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of
            the domain name
            <a href="https://magicalbrands.info/"
                class="text-blue-600 font-semibold hover:underline">magicalbrands.info</a> ('Website'),
            including the related mobile site and mobile application (hereinafter referred to as 'Platform').
        </p>
        <p class="text-gray-700 mt-3">
            By accessing or using our website, you agree to the terms of this <span class="font-medium">Privacy
                Policy</span>.
        </p>
    </section>

    <section class="mb-5 p-6 bg-gray-100 rounded-lg shadow-md">
        {{-- <h2 class="text-2xl font-semibold text-gray-800 mb-4">2. Information We Collect</h2> --}}
        <p class="text-gray-700 leading-relaxed">
            The Platform is owned by <strong>MM ENTERPRISES</strong>, a company incorporated under the <strong>Companies
                Act, 1956</strong>,
            with its registered office at <span class="font-medium">RZ A 139, Old Plot No. 138, Gali No. 1, Sitapuri
                Part 1, New Delhi</span>
            (hereinafter referred to as <strong>"Platform Owner"</strong>, <strong>'we'</strong>, <strong>'us'</strong>,
            <strong>'our'</strong>).
        </p>
    </section>

    <section class="mb-5 p-6 bg-gray-100 rounded-lg shadow-md">
        {{-- <h2 class="text-2xl font-semibold text-gray-800 mb-4">3. Use of Your Information</h2> --}}
        <p class="text-gray-700 leading-relaxed">
            Your use of the Platform, services, and tools is governed by the following terms and conditions
            (<strong>"Terms of Use"</strong>) as applicable to the Platform, including the applicable policies, which
            are incorporated herein by reference.
            If you transact on the Platform, you shall be subject to the policies that are applicable to such
            transactions.
        </p>
        <p class="text-gray-700 leading-relaxed mt-3">
            By merely using the Platform, you enter into a contract with the <strong>Platform Owner</strong>, and these
            Terms of Use, along with the policies,
            constitute your binding obligations. These Terms of Use relate to your use of our website, goods (as
            applicable), or services (as applicable)
            (collectively, <strong>"Services"</strong>).
        </p>
        <p class="text-gray-700 leading-relaxed mt-3">
            Any additional or conflicting terms and conditions proposed by you are expressly rejected by the Platform
            Owner and shall be of no force or effect.
            These Terms of Use may be modified at any time without prior notice. It is your responsibility to
            periodically review these Terms of Use to stay informed of updates.
        </p>
    </section>

    <section class="mb-5 p-6 bg-gray-100 rounded-lg shadow-md">
        {{-- <h2 class="text-2xl font-semibold text-gray-800 mb-4">4. Sharing Your Information</h2> --}}
        <p class="text-gray-700 leading-relaxed">
            For the purpose of these <strong>Terms of Use</strong>, wherever the context so requires,
            <strong>"you"</strong>, <strong>"your"</strong>, or <strong>"user"</strong> shall mean any natural or legal
            person
            who has agreed to become a user/buyer on the Platform.
        </p>
    </section>

    <section class="mb-5 p-6 bg-gray-100 rounded-lg shadow-md">
        {{-- <h2 class="text-2xl font-semibold text-gray-800 mb-4">5. Data Security</h2> --}}
        <p class="text-gray-700 leading-relaxed font-medium uppercase">
            Accessing, browsing, or otherwise using the Platform indicates your agreement to all the terms and
            conditions
            under these <strong>Terms of Use</strong>. Please read the Terms of Use carefully before proceeding.
        </p>
    </section>

    <section class="mb-5 p-6 bg-gray-100 rounded-lg shadow-md">
        {{-- <h2 class="text-2xl font-semibold text-gray-800 mb-4">6. Your Rights</h2> --}}
        <p class="text-gray-700 text-sm md:text-base leading-relaxed mb-4">
            The use of the Platform and/or availing of our Services is subject to the following Terms of Use:
        </p>
        <ul class="list-disc pl-5 space-y-3 text-gray-700 text-sm md:text-base leading-relaxed">
            <li><span class="font-medium">To access and use the Services</span>, you agree to provide true, accurate,
                and complete information during and after registration, and you shall be responsible for all acts done
                through your registered account on the Platform.</li>
            <li>Neither we nor any third parties provide any warranty or guarantee as to the <span
                    class="font-medium">accuracy, timeliness, performance, completeness, or suitability</span> of the
                information and materials offered on this website or through the Services, for any specific purpose. You
                acknowledge that such information and materials may contain inaccuracies or errors, and we expressly
                exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>
            <li>Your use of our Services and the Platform is <span class="font-medium">solely at your own risk and
                    discretion</span>, for which we shall not be liable. You are required to independently assess and
                ensure that the Services meet your requirements.</li>
            <li>The contents of the Platform and the Services are <span class="font-medium">proprietary to us</span> and
                are licensed to us. You will not have any authority to claim any intellectual property rights, title, or
                interest in its contents, including but not limited to the design, layout, look, and graphics.</li>
            <li>You acknowledge that <span class="font-medium">unauthorized use</span> of the Platform and/or the
                Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
            <li>You agree to <span class="font-medium">pay us the charges</span> associated with availing the Services.
            </li>
            <li>You agree not to use the Platform and/or Services for any purpose that is <span
                    class="font-medium">unlawful, illegal, or forbidden</span> by these Terms or applicable Indian/local
                laws.</li>
            <li>You agree and acknowledge that the website and the Services may contain links to other <span
                    class="font-medium">third-party websites</span>. Upon accessing these links, you will be governed by
                the terms of use, privacy policy, and other policies of such third-party websites. These links are
                provided for your convenience to offer further information.</li>
            <li>You understand that upon initiating a transaction for availing the Services, you are entering into a
                <span class="font-medium">legally binding and enforceable contract</span> with the Platform Owner.
            </li>
            <li>You shall <span class="font-medium">indemnify and hold harmless</span> the Platform Owner, its
                affiliates, group companies (as applicable), and their respective officers, directors, agents, and
                employees from any claim, demand, or actions, including reasonable attorney's fees, made by any third
                party or penalty imposed due to or arising out of your breach of this Terms of Use, Privacy Policy, and
                other Policies, or your violation of any law, rules, or regulations, or the rights (including
                infringement of intellectual property rights) of a third party.</li>
            <li>Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any <span
                    class="font-medium">failure to perform</span> an obligation under these Terms if performance is
                prevented or delayed by a force majeure event.</li>
            <li>These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and
                construed in accordance with the <span class="font-medium">laws of India</span>.</li>
            <li>All disputes arising out of or in connection with these Terms shall be subject to the <span
                    class="font-medium">exclusive jurisdiction</span> of the courts in New Delhi and Delhi.</li>
        </ul>
    </section>


    <section class="mb-5 p-6 bg-gray-100 rounded-lg shadow-md border-l-4 border-blue-500">
        {{-- <h2 class="text-2xl font-semibold text-gray-800 mb-4">7. Third-Party Links</h2> --}}
        <p class="text-gray-700 text-sm md:text-base leading-relaxed">
            All concerns or communications related to these Terms must be directed to us using the
            <span class="font-medium">contact information</span> provided on this website.
        </p>
        <p class="text-gray-700 mt-2">
            For more details, please refer to our website.
        </p>
    </section>

   
</div>
@endsection